## Lesson: 1  Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model's parameters.

### Import dependeries 

In [29]:
import torch
import numpy as np

## Initializing a Tensor

Tensor can be initialized in various ways. we look at the following examples:

## Directely from data

Tensors can be created directly from data. The data types is automatically inferred.

In [30]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

## From a NumPy array

Tensors can be created from NumPy arrays (and vice versa)


In [31]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

## From another tensor:

#### The new tensor retains the properties(shape,datatype) of the argument tensor, unless explicitly overridden.

In [32]:
x_ones = torch.ones_like(x_data)  # retains the properies of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype = torch.float)  # overrides the datatypes of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3333, 0.4060],
        [0.9496, 0.1707]]) 



## with random or constant values:

Shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionlity of the output tensor.

In [33]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.5516, 0.1683, 0.6740],
        [0.9434, 0.3242, 0.2646]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## Attributes of a Tensor

Tensor attributes describe their shape, datatype and the devie on which they are stored.

In [34]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device of tensor: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device of tensor: cpu


## Operations on Tensors

Over 100 tensor operations, including arithmatic, linear algebra, matrix manipulation(transposing, indexing, slicing), sampling and many more can be done.


Each of these operations can be run on the GPU(at typically higher speeds tha in a CPU). If you're usig Colab, allocate a GPU by going to runtime> Change runtime tpye >GPU.


by default, tensors are created on the CPU. We need to explicitly move tensors to the GPU usig **.to** method (after checking for GPU availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [35]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

Try out some of the operations from the list. If you are familiar with NumPy API, you'll find the Tensor API a breeze to use.

### Standard numpu-like indexing and slicing

In [36]:
tensor = torch.ones(4,4)
print(f"Tensor first row: {tensor[0]}")
print(f"Tensor first column: {tensor[:,0]}")
print(f"Tensor last column: {tensor[...,-1]}")
tensor[:,1] =0
print(tensor)

Tensor first row: tensor([1., 1., 1., 1.])
Tensor first column: tensor([1., 1., 1., 1.])
Tensor last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## Joining tensors 

you can use **torch.cat** to concatenate a sequence of tensors alonga given dimension. See also torch.stack, another tensor joining option that is subtly different from **torch.cat**.

In [37]:
t1 = torch.cat([tensor, tensor], dim =1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]])


### Arthematic Operations

In [38]:
# This compute the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# "tensor.T" return the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

# This compute the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

## Single-element tensors

if you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numberical value using **item():**

In [39]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


## In-place operations

Operations that store the result into the operand are called in-place. They are denoted by a_suffix. For example: x.copy_(y), x.t_(), will change x.


In [40]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# Bridge with NumPy

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

## Tensor to NumPy array

In [41]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array

In [42]:
t.add_(2)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]


### NumPy array to Tensor

In [43]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor

In [45]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
n: [3. 3. 3. 3. 3.]
